nhbackend-rel:
    image: registry-vpc.cn-shanghai.aliyuncs.com/backend-rel:latest
    links:
        - redis3:redis3
        - es-indices-master:es-master
    labels:
        aliyun.depends: redis3,es-indices-master,es-indices-data
        aliyun.scale: '2'
        aliyun.routing.port_8080: domain1;domain2
        aliyun.probe.url: http://container:8080/nakedhub/
        aliyun.probe.timeout_seconds: '60'
        aliyun.probe.initial_delay_seconds: '3'
        aliyun.rolling_updates: 'true'
    logging:
        driver: fluentd
        options:
            fluentd-address: '1.1.1.1:24223'
            tag: 'rel.backend'
    volumes:
        - 'acs-shared:/nfs:rw'
    environment:
        JAVA_OPTS: '$JAVA_OPTS -server -Xms2048m -Xmx2048m -Dspring.profiles.active=tomcat,release -Djava.security.egd=file:/dev/urandom -Dhibernate.search.default.elasticsearch.host="http://nhbackend_es-indices-master_1:9200/ http://nhbackend_es-indices-master_2:9200/" -Dglobal.redis.hostname=redis3 -Dglobal.redis.password= -Dglobal.database.url=jdbc:mysql://host:3306/dbname -Dglobal.database.username=xxx -Dglobal.database.password=xxx'
ngscheduler-rel:
    image: registry-vpc.cn-shanghai.aliyuncs.com/scheduler-rel:latest
    labels:
        aliyun.depends: nhbackend-rel
        aliyun.scale: '1'
    logging:
        driver: fluentd
        options:
            fluentd-address: '1.1.1.1:24223'
    environment:
        spring.profiles.active: 'rel'
redis3:
    image: redis:3.2.10
es-indices-master:
    image: registry-vpc.cn-shanghai.aliyuncs.com/elasticsearch-indices:1
    entrypoint:
        - /docker-entrypoint.sh
    command:
        - elasticsearch
        - -Des.cluster.name=escluster
        - -Des.node.master=true
        - -Des.node.data=false
        - -Des.network.host=_eth0_
        - -Des.discovery.zen.ping.unicast.hosts=nhbackend_es-indices-master_1,nhbackend_es-indices-master_2
    labels:
        aliyun.routing.port_9200: elasticsearch2
        aliyun.scale: '3'
es-indices-data:
    image: registry-vpc.cn-shanghai.aliyuncs.com/elasticsearch-indices:1
    entrypoint:
        - /docker-entrypoint.sh
    command:
        - elasticsearch
        - -Des.cluster.name=escluster
        - -Des.node.ingest=false
        - -Des.node.master=false
        - -Des.network.host=_eth0_
        - -Des.discovery.zen.ping.unicast.hosts=nhbackend_es-indices-master_1,nhbackend_es-indices-master_2
    labels:
        aliyun.depends: es-indices-master
        aliyun.scale: '3'