version: '2'

services:
  server1:
    image: consul
    command:
      - agent
      - -server
      - -bootstrap-expect=1
      - -data-dir=/tmp/consul
      - -node=agent-server1
      - -node-id=F9EA7391-B05A-F8E5-2B3A-0B5ACB3DDDB8

  client1:
    image: consul
    depends_on:
      - server1
    ports:
      - '8800:8500'
    command:
      - agent
      - -ui
      - -client=0.0.0.0
      - -data-dir=/tmp/consul
      - -node=agent-client1
      - -node-id=AF8340DA-61B8-EDA2-B3C1-4791D05FB688
      - -join=server1
