version: '2'

services:
 es-indices-master:
   container_name: es-indices-master
   image: registry.cn-shanghai.aliyuncs.com/ng/elasticsearch-indices:4
   entrypoint:
       - /docker-entrypoint.sh
   command:
       - elasticsearch
       - -Des.cluster.name=escluster
       - -Des.node.master=true
       - -Des.node.data=false
       - -Des.path.repo=/backup
   volumes:
       - es-databackup:/backup:rw
   ports:
       - "9201:9200"

 es-indices-data1:
   container_name: es-indices-data1
   image: registry.cn-shanghai.aliyuncs.com/ng/elasticsearch-indices:4
   entrypoint:
       - /docker-entrypoint.sh
   command:
       - elasticsearch
       - -Des.cluster.name=escluster
       - -Des.node.ingest=false
       - -Des.node.master=false
       - -Des.path.repo=/backup
       - -Des.discovery.zen.ping.unicast.hosts=es-master
   volumes:
       - es-databackup:/backup:rw
   links:
       - "es-indices-master:es-master"

 es-indices-data2:
   container_name: es-indices-data2
   image: registry.cn-shanghai.aliyuncs.com/ng/elasticsearch-indices:4
   entrypoint:
       - /docker-entrypoint.sh
   command:
       - elasticsearch
       - -Des.cluster.name=escluster
       - -Des.node.ingest=false
       - -Des.node.master=false
       - -Des.path.repo=/backup
       - -Des.discovery.zen.ping.unicast.hosts=es-master
   volumes:
       - es-databackup:/backup:rw
   links:
       - "es-indices-master:es-master"

volumes:
   es-databackup: