es-indices-master:
    image: 'registry.cn-hangzhou.aliyuncs.com/nakedgroup/elasticsearch-indices:1'
    entrypoint:
        - /docker-entrypoint.sh
    command:
        - elasticsearch
        - -Des.cluster.name=escluster
        - -Des.node.master=true
        - -Des.node.data=false
        - -Des.network.host=_eth0_
        - -Des.discovery.zen.minimum_master_nodes=1
    environment:
        ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    labels:
        aliyun.routing.port_9200: elasticsearch2
        aliyun.scale: '2'
es-indices-data:
    image: 'registry.cn-hangzhou.aliyuncs.com/nakedgroup/elasticsearch-indices:1'
    entrypoint:
        - /docker-entrypoint.sh
    command:
        - elasticsearch
        - -Des.cluster.name=escluster
        - -Des.node.ingest=false
        - -Des.node.master=false
        - -Des.network.host=_eth0_
        - -Des.discovery.zen.ping.unicast.hosts=nhbackend_es-indices-master_1,nhbackend_es-indices-master_2
    environment:
        ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    labels:
        aliyun.depends: es-indices-master
        aliyun.scale: '2'
