version: '2'

services:
  elasticsearch-xpack5:
    build: ./elasticsearch-xpack5
    ports: 
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    restart: always
  fluentd-es:
    build: ./fluentd-es
    depends_on: 
      - elasticsearch-xpack5
    ports:
      - "24224:24224"
    restart: always
  kibana-xpack5:
    build: ./kibana-xpack5
    depends_on:
      - elasticsearch-xpack5
      - fluentd-es
    ports:
      - "5602:5601"
    environment:
      ELASTICSEARCH_URL: 'http://172.16.1.12:9200'
      XPACK_MONITORING_ENABLED: 'false'
    restart: always
