version: '2'

services:
  elk-elasticsearch:
    build: ./elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    restart: always
    networks:
      - elk
  elk-fluentd:
    build: ./fluentd
    depends_on: 
      - elk-elasticsearch
    ports:
      - "24224:24224"
    restart: always
    networks:
      - elk
  elk-kibana:
    build: ./kibana
    depends_on:
      - elk-elasticsearch
      - elk-fluentd
    ports:
      - "5602:5601"
    environment:
      ELASTICSEARCH_URL: 'http://elk-elasticsearch:9200'
      XPACK_MONITORING_ENABLED: 'false'
    restart: always
    networks:
      - elk

networks:
  elk:
    external: true
