version: '2'

services:
  elk-elasticsearch:
    container_name: elk-elasticsearch
    image: elasticsearch:5.1.1
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    restart: always

  elk-fluentd:
    container_name: elk-fluentd
    build: ./fluentd
    depends_on: 
      - elk-elasticsearch
    ports:
      - "24224:24224"
    restart: always

  elk-kibana:
    container_name: elk-kibana
    image: kibana:5.1.1
    depends_on:
      - elk-elasticsearch
      - elk-fluentd
    ports:
      - "5602:5601"
    environment:
      ELASTICSEARCH_URL: 'http://elk-elasticsearch:9200'
      XPACK_MONITORING_ENABLED: 'false'
    restart: always