version: '2'

services:
  mysqla:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3301:3306'
    command:
      - "--log_bin=mysql-bin"
      - "--binlog_format=ROW"
      - "--server_id=101"
    networks:
      otter_net:
        ipv4_address: 10.0.1.3

  mysqlb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3302:3306'
    command:
      - "--log_bin=mysql-bin"
      - "--binlog_format=ROW"
      - "--server_id=102"
    networks:
      otter_net:
        ipv4_address: 10.0.1.6

  zkServer1:
    image: zookeeper:3.3.6
    networks:
      otter_net:
        ipv4_address: 10.0.0.3

  managerdb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3333:3306'
    networks:
      otter_net:
        ipv4_address: 10.0.1.9

  manager:
    image: openjdk:8u131-jdk-alpine
    ports:
      - '8888:8080'
    command:
      - sh
      - -c
      - 'while true; do sleep 2; done'
    networks:
      otter_net:
        ipv4_address: 10.0.0.5

  node1:
    image: openjdk:8u131-jdk-alpine
    command:
      - sh
      - -c
      - 'while true; do sleep 2; done'
    networks:
      otter_net:
        ipv4_address: 10.0.0.6

#  canal1:
#    image: openjdk:8u131-jdk-alpine
#    command:
#      - sh
#      - -c
#      - 'while true; do sleep 2; done'

  node2:
    image: openjdk:8u131-jdk-alpine
    command:
      - sh
      - -c
      - 'while true; do sleep 2; done'
    networks:
      otter_net:
        ipv4_address: 10.0.0.7

#  canal2:
#    image: openjdk:8u131-jdk-alpine
#    command:
#      - sh
#      - -c
#      - 'while true; do sleep 2; done'
networks:
  otter_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.0.0/16